#!/bin/bash

cleanup() {
    echo "Shutting up..."
    killall -s SIGINT ros2
}
# Trap termination signals and call the cleanup function
trap cleanup SIGTERM SIGINT

/usr/bin/bash -c 'source /opt/ros/jazzy/setup.bash && source /home/ubu/ros2_ws/install/setup.bash && ros2 run te_uas remote_fly.launch'
wait